authors_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('authors/', views.author_list, name='author_list'),
    path('authors/new/', views.author_new, name='author_new'),
    path('authors/sort_by_articles', views.author_sort_by_articles, name='author_sort_by_articles'),
    path('authors/sort_by_articles_reverse', views.author_sort_by_articles_reverse, name='author_sort_by_articles_reverse'),
    path('authors/<int:pk>/', views.author_detail, name='author_detail'),
    path('authors/<int:pk>/edit/', views.author_edit, name='author_edit'),
    path('authors/<int:pk>/remove/', views.author_remove, name='author_remove'),
    path('articles/sort_by_authors', views.article_sort_by_authors, name='article_sort_by_authors'),
    path('articles/sort_by_authors_reverse', views.article_sort_by_authors_reverse, name='article_sort_by_authors_reverse'),
    path('articles/new/', views.article_new, name='article_new'),
    path('articles/<int:pk>/', views.article_detail, name='article_detail'),
    path('articles/<int:pk>/edit/', views.article_edit, name='article_edit'),
    path('articles/<int:pk>/remove/', views.article_remove, name='article_remove'),
]

authors_site/urls.py
from django.contrib import admin
from django.urls import path, include

# for api
from rest_framework import routers
from authors_app import views

router = routers.DefaultRouter()
router.register(r'api/articles', views.ArticlesViewSet)
router.register(r'api/authors', views.AuthorsViewSet)
router.register(r'api/publications', views.PublicationViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authors_app.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

authors_app/models.py
from django.utils import timezone
from django.db import models


class Authors(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name


class Articles(models.Model):
    title = models.CharField(max_length=200, null=False)
    text = models.TextField(null=False)
    publications = models.ManyToManyField(Authors, through='Publication')

    def __str__(self):
        return self.title


class Publication(models.Model):
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)

    # publication_date = models.DateTimeField(auto_now_add=True, null=True)
    # publication_date = models.DateTimeField(default=timezone.now, null=True)

authors_app/forms.py
from django import forms
from .models import Articles, Authors


class AuthorForm(forms.ModelForm):
    
    class Meta:
        model = Authors
        labels = {
            "name": "Введите имя автора"
        }
        fields = ['name']



class ArticleForm(forms.ModelForm):
    
    class Meta:
        model = Articles
        labels = {
            "title": "Название статьи",
            "text": "Текст статьи"
        }
        exclude = ['publications']

authors_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from .models import Articles, Authors, Publication
from .forms import AuthorForm, ArticleForm

from rest_framework import viewsets
from .serializers import ArticlesSerializer, AuthorsSerializer, PublicationSerializer


class ArticlesViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows articles to be viewed or edited.
    """
    queryset = Articles.objects.all().order_by('-title')
    serializer_class = ArticlesSerializer


class AuthorsViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows authors to be viewed or edited.
    """
    queryset = Authors.objects.all()
    serializer_class = AuthorsSerializer


class PublicationViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows authors to be viewed or edited.
    """
    queryset = Publication.objects.all()
    serializer_class = PublicationSerializer


def article_list(request):
    """
    Список статей
    """

    articles = Articles.objects.all()
    return render(request, 'authors_app/article_list.html', context={
        'articles': articles,
    })


def article_sort_by_authors(request):
    """
    Сортировка статей по количеству авторов (от большего количества к меньшему)
    """

    articles = Articles.objects.annotate(Count('publications')).order_by("publications__count").reverse()
    return render(request, 'authors_app/article_list.html', context={
        'articles': articles,
    })


def article_sort_by_authors_reverse(request):
    """
    Сортировка статей по количеству авторов (от меньшего количества к большему)
    """

    articles = Articles.objects.annotate(Count('publications')).order_by("publications__count")

    return render(request, 'authors_app/article_list.html', context={
        'articles': articles,
    })


def article_detail(request, pk):
    """
    Детальная информация о статье
    """

    article = get_object_or_404(Articles, pk=pk)
    authors = Authors.objects.filter(articles__id=pk)
    return render(request, 'authors_app/article_detail.html', context={
        'article': article,
        'authors': authors
    })


def article_edit(request, pk):
    """
    Редактирование статьи
    """

    article = get_object_or_404(Articles, pk=pk)
    page_title = 'Редактирование статьи'

    if request.method == "POST":
        article_form = ArticleForm(request.POST, instance=article)
        author_form = AuthorForm(request.POST)

        if article_form.is_valid() and author_form.is_valid():
            article.save()
            author = author_form.save(commit=False)

            # add for article if the author is registred
            if Authors.objects.filter(name=author.name):
                author = Authors.objects.get(name=author.name)
                Publication.objects.create(author=author, article=article)

            return redirect('article_detail', pk=article.pk)
    else:
        article_form = ArticleForm(instance=article)
        author_form = AuthorForm()
        author_form.fields['name'].label = "Добавить автора"

    article = Articles.objects.get(pk=pk)
    authors_list = [d['name'] for d in (list(article.publications.values('name')))]

    return render(request, 'authors_app/article_edit.html', context={
        'article_form': article_form,
        'author_form': author_form,
        'page_title': page_title,
        'authors_list': authors_list,
        'article': article
    })


def article_new(request):
    """
    Создание новой статьи
    """
    page_title = 'Создание новой статьи'

    if request.method == "POST":
        article_form = ArticleForm(request.POST)
        author_form = AuthorForm(request.POST)

        if article_form.is_valid() and author_form.is_valid():
            author = author_form.save(commit=False)

            # if the author exists with this name, don't create
            if not Authors.objects.filter(name=author.name):
                author = author_form.save()
            else:
                author = Authors.objects.get(name=author.name)

            article = article_form.save(commit=False)
            # if the article exists with this title, don't create
            if not Articles.objects.filter(title=article.title):
                article = article_form.save()
            else:
                article = Articles.objects.get(title=article.title)

            Publication.objects.create(author=author, article=article)
            return redirect('article_detail', pk=article.pk)
    else:
        author_form = AuthorForm()
        article_form = ArticleForm()

    return render(request, 'authors_app/article_edit.html', context={
        'article_form': article_form,
        'author_form': author_form,
        'page_title': page_title,
    })


def article_remove(request, pk):
    """
    Удаление статьи
    """
    # article = get_object_or_404(Articles, pk=pk)
    article = Articles.objects.get(id=pk)
    title = article.title
    authors_inst = article.publications.filter().values('name')
    authors_list = [d['name'] for d in list(authors_inst.values('name'))]

    print(title, authors_list)

    article.delete()
    return render(request, 'authors_app/article_remove.html', context={
        'title': title,
        'authors_list': authors_list
    })


def author_list(request):
    """
    Список авторов
    """

    authors = Authors.objects.all()
    return render(request, 'authors_app/author_list.html', context={'authors': authors})


def author_sort_by_articles(request):
    """
    Сортировка авторов по количеству статей от большего количества к меньшему
    """

    authors = Authors.objects.annotate(Count('articles')).\
        order_by("articles__count").reverse()
    return render(request, 'authors_app/author_list.html', context={'authors': authors})


def author_sort_by_articles_reverse(request):
    """
    Сортировка авторов по количеству статей от меньшего количества к большему
    """

    authors = Authors.objects.annotate(Count('articles')).\
        order_by("articles__count")
    return render(request, 'authors_app/author_list.html', context={'authors': authors})


def author_detail(request, pk):
    """
    Детальная информация об авторе
    """

    author = get_object_or_404(Authors, pk=pk)
    return render(request, 'authors_app/author_detail.html', context={
        'author': author
    })


def author_new(request):
    """
    Добавление нового автора
    """

    page_title = 'Регистрация автора'

    if request.method == "POST":
        author_form = AuthorForm(request.POST)
        if author_form.is_valid():
            author_inst = author_form.save(commit=False)

            # if the author exists with this name, don't create
            if not Authors.objects.filter(name=author_inst.name):
                author = author_form.save()
            else:
                author = Authors.objects.get(name=author_inst.name)

            return redirect('author_detail', pk=author.pk)
    else:
        author_form = AuthorForm()

    return render(request, 'authors_app/author_edit.html', context={
        'author_form': author_form,
        'page_title': page_title,
    })


def author_edit(request, pk):
    """
    Редактирование информации об авторе
    """

    author = get_object_or_404(Authors, pk=pk)
    page_title = 'Редактирование автора'

    if request.method == "POST":
        author_form = AuthorForm(request.POST, instance=author)
        if author_form.is_valid():
            author.save()
            return redirect('author_detail', pk=author.pk)
    else:
        author_form = AuthorForm(instance=author)

    return render(request, 'authors_app/author_edit.html', context={
        'author_form': author_form,
        'page_title': page_title,
    })


def author_remove(request, pk):
    """
    Удаление автора (всех его личных статей, удаление из других статей как соавтора)
    """

    author = Authors.objects.get(id=pk)
    name = author.name

    for publication in Publication.objects.filter(article_id=author.id):
        publication.remove(author)

    author_articles = Articles.objects.annotate(Count('publication__author_id')).filter(publication__author_id=pk)
    # single author
    for article in author_articles.filter(publication__author_id__count=1):
        article_inst = Articles.objects.get(id=article.id)
        print('single')
        article_inst.delete()

    author.delete()

    return render(request, 'authors_app/author_remove.html', context={
        'name': name,
    })

authors_app/templates/authors_app/article_detail.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <div class="article">
        <h1>Информация о статье</h1>
        <h4>
            Автор{%if article.publications.all|length > 1 %}ы{% endif %}:
            {% for author in authors %}{{ author.name }}{% if not forloop.last %}, {% endif %}{% endfor %}
        </h4>
        <br>
        {% if user.is_authenticated %}
        	<a class="btn btn-default" href="{% url 'article_edit' pk=article.pk %}">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a class="btn btn-default" href="{% url 'article_remove' pk=article.pk %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        {% endif %}

        <h2>{{ article.title }}</h2>
        <p>{{ article.text|linebreaksbr }}</p>
    </div>
{% endblock %}

authors_app/templates/authors_app/article_edit.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <h4>
        {% if authors_list %}
        Автор{%if authors_list|length > 1 %}ы{% endif %}:&nbsp;&nbsp;
        {% endif %}
        {% for author in authors_list%}{{author}}{% if not forloop.last %}, {% endif %}{% endfor%}
    </h4>
    <form method="POST" class="article-form">
    	{% csrf_token %}
        {{ author_form.as_p }}
        {{ article_form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

authors_app/templates/authors_app/article_list.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <div class="article">
    {% if articles|length > 0 %}
        <h1>Статьи в каталоге:</h1>
        <a class="btn btn-default" href="{% url 'article_sort_by_authors' %}">
            <span class="glyphicon glyphicon-arrow-up"></span>
        </a>
        <a class="btn btn-default" href="{% url 'article_sort_by_authors_reverse' %}">
            <span class="glyphicon glyphicon-arrow-down"></span>
        </a>
        {% for article in articles %}
            <h3>
                <li>
                    <a href="{% url 'article_detail' pk=article.pk %}">{{ article.title }}</a>
                    {% if article.publications__count >= 0 %}
                        (количество авторов: {{article.publications__count}} )
                    {% endif %}
                </li>
            </h3>
        {% endfor %}
    {% else %}
        <h1>В каталоге нет статей</h1>
    {% endif%}
    </div>
{% endblock %}

authors_app/templates/authors_app/article_remove.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <!--<h1>Пока ничего не произошло, но это случится. Верь в лучшее!</h1>-->
    <form method="POST" class="article-form">
    	{% csrf_token %}
        <h3>Удалена статья "{{title}}", которую создали авторы:<br>
            <h4>
                {% for author in authors_list %} <li>{{ author }}</li> {% endfor %}
            </h4>
        </h3>
        <div class="article">
            <h3><a href="{% url 'article_list' %}">Вернуться к списку статей</a></h3>
        </div>
    </form>
{% endblock %}

authors_app/templates/authors_app/author_detail.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <div class="article">
        {% if user.is_authenticated %}
        	<a class="btn btn-default" href="{% url 'author_edit' pk=author.pk %}">
                <span class="glyphicon glyphicon-pencil"></span>
            </a>
            <a class="btn btn-default" href="{% url 'author_remove' pk=author.pk %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        {% endif %}
        <h2>{{author.name}}</h2>
        <h4>
            Количество статей: {{author.articles_set.count}}<br><br>
            {% if author.articles_set.count > 0 %}
            Статьи:
            {% for article in author.articles_set.all %}<li>{{ article.title }}</li>{% endfor %}
            {% endif %}
        </h4>
    </div>
{% endblock %}

authors_app/templates/authors_app/author_edit.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <h1>{{ page_title }}</h1>
    <form method="POST" class="article-form">
    	{% csrf_token %}
        {{ author_form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

authors_app/templates/authors_app/author_list.html
{% extends 'authors_app/base.html' %}

{% block content %}
    {% if authors|length > 0 %}
        <h1>Зарегистрированные авторы:</h1>
        <a class="btn btn-default" href="{% url 'author_sort_by_articles' %}">
            <span class="glyphicon glyphicon-arrow-up"></span>
        </a>
        <a class="btn btn-default" href="{% url 'author_sort_by_articles_reverse' %}">
            <span class="glyphicon glyphicon-arrow-down"></span>
        </a>
        {% for author in authors %}
            <div>
                <h3><a href="{% url 'author_detail' pk=author.pk %}">{{ author.name }}</a>
                {% if author.articles__count >= 0 %}
                    (количество статей: {{author.articles__count}})
                {% endif %}
                </h3>
            </div>
        {% endfor %}
    {% else %}
        <h1>Список авторов пуст</h1>
    {% endif %}
{% endblock %}

authors_app/templates/authors_app/author_remove.html
{% extends 'authors_app/base.html' %}

{% block content %}
    <!--<h1>Пока ничего не произошло, но это случится. Верь в лучшее!</h1>-->
    <form method="POST" class="article-form">
    	{% csrf_token %}
        <h3>Автор {{name}} и все его статьи (с единственным авторством) удалены!</h3>
        <div class="article">
            <h3><a href="{% url 'author_list' %}">Вернуться к списку авторов</a></h3>
        </div>
    </form>
{% endblock %}

authors_app/templates/authors_app/base.html
{% load static %}
<html>
    <head>
        <title>Authors & Articles</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" type='text/css'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css" type='text/css'>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" type="text/css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Serif+Pro&display=swap">
        <link rel="stylesheet" href="{% static 'css/authors_app.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'author_list' %}" class="top-menu"><span class="glyphicon glyphicon-list"></span></a>
            {% if user.is_authenticated %}
            <a href="{% url 'article_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <a href="{% url 'author_new' %}" class="top-menu"><span class="glyphicon glyphicon-user"></span></a>
            {% endif %}
            <h1><a href="/" class="title">Authors & Articles</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>